### ISSUE TITLE
Add Documentation on how to use with decorators

### ISSUE THREAD

**Issue by NullVoxPopuli** [NullVoxPopuli/react-state-helpers#9]
There are lots of options for names -- not really sure on a convention for _all_ decorators yet -- or even if it matters -- maybe it depends on what the decorator does.

example:

```js
import React, { Component } from 'react';
import wrapStateHelpers from 'react-state-helpers';

@wrapStateHelpers
export default class MyComponent extends Component { ... }
```

Not sure of the recommended default export name should be an action, a noun, or an -able suffix. 

/cc @PorterK

**Comment by PorterK** [comment]
I like it to be an action, you're _doing_ something to the class/function that you're decorating. Seems logical.

If you put `@wrapper` it kind of makes it seem like you're describing the class as a wrapper class, not wrapping the class in something.

Those are my thoughts on it :)

**Comment by PorterK** [comment]
Putting up a PR for this soon 😄

**Comment by PorterK** [comment]
Closing, merged PR
